---
- name: Create Azure key vault
  hosts: localhost
  connection: local
  vars:
    container_registry_name: "testacrjk01"
    rg_group_name: "dev01resourcegroupjk02"
    location_name: "centralindia"
    aks_name: "asktestjk01"
    user_name: "askuser01"
    ssh_pub_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDDFHyNnTOZYpuBUuvev6jG2J7jn4m8CBObOtdtSDy9Qwt87zmmqQ86Bt8JwHFKw9a7c5wSj32HD9rj1DZuw678e1a2a22gLN+XfTN0ohpYVWX1LgTKdsntfXcnqfy7y/P9TJ8szHzayfE4UisoSnUw78dhYYNhFftgk4V/57qRPYHeGTL97TCCeQ9+m29lvcgO7pbI94iq1VJyl6NyBxqBgB18L/UHciAWPJ2dmHhy+9VTba2UwaPArK8/mOMG+lO++h/cb1P/Ctn17aW935pfb/WtNG3dfxGJYxtWIlS9tzGI6pdfo5XaefQA0k2XwzE09Vo0Z3c4xWZPcEi61a8kwIa7BEvaoBkMDvxmcbHCKDs8On3hXF6Kr23VZtNQRRxDjPFrntvwLWUf3haBOfrDPh8xX++t6ZYgONMj3oiDdZqHGbz7W1TrS477AdUTuVjLWoJApv/tYMEFf8at9EO+i4kMH9HRQo8Xaqq8Wm1dCtZ3gMp4GXWjmRF0F+Tvi4s= root@ansibletower02.devops.jk.org"
    client_id: "215046e5-2683-4633-9529-411a41190ca9"
    client_secret: "69fc600f-e22a-4549-aa7e-a5c194091aa0" 
    k8s_version: "1.21.2"
    environment_name: "DEV"
  tasks:
  - name: 1 Create resource group
    azure_rm_resourcegroup:
      name: "{{rg_group_name}}"
      location: "{{location_name}}"
      tags:
        Environment: "{{environment_name}}"
      

  - name: 2 Create an azure container registry
    azure_rm_containerregistry:
      name: "{{container_registry_name}}"
      location: "{{location_name}}"
      resource_group: "{{rg_group_name}}"
      admin_user_enabled: true
      sku: Standard
      tags:
        Environment: "{{environment_name}}"
        Release: beta1
        
  - name: 3 Create a managed Azure Container Services (AKS) instance
    azure_rm_aks:
      name: "{{aks_name}}"
      location: "{{location_name}}"
      resource_group: "{{rg_group_name}}"
      kubernetes_version: "{{k8s_version}}"
      dns_prefix: asktestjk01
      linux_profile:
        admin_username: "{{user_name}}"
        ssh_key: "{{ssh_pub_key}}"
      service_principal:
        client_id: "{{client_id}}"
        client_secret: "{{client_secret}}"
      agent_pool_profiles:
        - name: default
          count: 2
          vm_size: Standard_D2_v2
      tags:
        Environment: "{{environment_name}}" 