---
- name: Create Azure resource group
  hosts: localhost
  connection: local
  
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: myresourcegroup-jk
        location: centralindia
        tags:
          environment: DEV
          
    - name: Create a virtual network
      azure_rm_virtualnetwork:
        resource_group: myresourcegroup-jk
        name: myvirtualnetworkjktower
        address_prefixes_cidr: "10.1.0.0/16"
        tags:
          environment: DEV
          
    - name: Create a virtual subnet
      azure_rm_subnet:
        resource_group: myresourcegroup-jk
        virtual_network_name: myvirtualnetworkjktower
        name: myvirtualnetworkjktower-subnet
        address_prefix_cidr: "10.1.0.0/24"
        
    - name: Create a public IP address
      azure_rm_publicipaddress:
        resource_group: myresourcegroup-jk
        name: myvirtualnetworkjk_public_ip
        allocation_method: static
      register: myvirtualnetworkjk_public_ip      

    - name: Create a security group to allow SSH    
      azure_rm_securitygroup:
        resource_group: myresourcegroup-jk
        name: mysecgroupjk
        purge_rules: yes
        rules:
          - name: 'AllowSSH'
            protocol: Tcp
            source_address_prefix:
              - '0.0.0.0/0'
            destination_port_range:
              - 22
              - 3389
            access: Allow
            priority: 100
            direction: Inbound
          - name: 'AllowMultiplePorts'
            protocol: Tcp
            source_address_prefix:
              - '0.0.0.0/0'
            destination_port_range:
              - 80
              - 443
            access: Allow
            priority: 101