---
- name: Create Azure resource group
  hosts: localhost
  connection: local
  vars:
    rg_group_name: "dev01resourcegroupjk"
  
  tasks:
    - name: 1 Create a resource group
      azure_rm_resourcegroup:
        name: "{{rg_group_name}}"
        location: centralindia
        tags:
          environment: "{{environment_name}}"