---
- name: Create Azure resource group
  hosts: localhost
  connection: local
  vars:
    - rg_group_name: jkresourcegroupdevweb01
    - app_service_name: jkappservicedevweb01
    - app_service_plan_name: myappserviceplan01
    - location: centralindia
    - environment_name: DEV
  
  tasks:
    - name: 1 Create a resource group
      azure_rm_resourcegroup:
        name: "{{rg_group_name}}"
        location: "{{location}}"
        tags:
          environment: "{{environment_name}}"
          
    - name: 2 Create a windows app service plan
      azure_rm_appserviceplan:
        resource_group: "{{rg_group_name}}"
        name: "{{app_service_plan_name}}"
        location: "{{location}}"
        sku: F1
        is_linux: true
        tags:
          environment: "{{environment_name}}"      
          
    - name: 3 Create a windows web app service with non-existing app service plan
      azure_rm_webapp:
        resource_group: "{{rg_group_name}}"
        name: "{{app_service_name}}"
        plan:
          resource_group: "{{rg_group_name}}"
          name: "{{app_service_plan_name}}"
          is_linux: true
          sku: F1
          tags:
          environment: "{{environment_name}}"
        
       
#https://azure.microsoft.com/en-us/pricing/details/app-service/windows/