---
- name: Create Azure key vault
  hosts: localhost
  connection: local
  vars:
    tenant_id: 8f286d24-172e-4e09-b0f0-76f2cf5786ea
    object_id: 3497c2d0-c971-4886-b8a3-05465f731417
    rg_group_name: "dev01resourcegroupjk02"
    location_name: "centralindia"
    vault_name: "samplekeyvaultjk02"
    environment_name: "DEV"
	
  tasks:
  - name: 1 Create resource group 
    azure_rm_resourcegroup:
      name: "{{rg_group_name}}"
      location: eastus

  - name: 2 Create instance of Key Vault
    azure_rm_keyvault:
      resource_group: "{{rg_group_name}}"
      vault_name: "{{ vault_name }}"
      enabled_for_deployment: yes
      vault_tenant: "{{ tenant_id }}"
      sku:
        name: standard
      access_policies:
        - tenant_id: "{{ tenant_id }}"
          object_id: "{{ object_id }}"
          secrets:
            - get
            - list
            - set
            - delete