---
- name: Create Azure resource group
  hosts: localhost
  connection: local
  vars:
    rg_group_name: "dev01resourcegroupjk"
    virtual_network_name: "dev01virtualnetworkjk"
    storage_account_name: "dev01storageaccountjk"
    public_ip_name: "dev01publicipjk"
    virtual_machine_name: "DEV01RHEL8JK2021"
    network_interface_card_name: "dev01networkinterfacecardjk"
    environment_name: "DEV"
  
  tasks:
    - name: 1 Create a resource group
      azure_rm_resourcegroup:
        name: "{{rg_group_name}}"
        location: centralindia
        tags:
          environment: "{{environment_name}}"
          
    - name: 2 Create a virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{rg_group_name}}"
        name: "{{virtual_network_name}}"
        address_prefixes_cidr: "10.1.0.0/16"
        tags:
          environment: "{{environment_name}}"