---
- name: Create Azure resource group
  hosts: localhost
  connection: local
  vars:
    - rg_group_name: jkresourcegroupdevweb01
    - app_service_name: jkappservicedevweb01
    - app_service_plan_name: myappserviceplan
    - environment_name: DEV
  
  tasks:
    - name: 1 Create a resource group
      azure_rm_resourcegroup:
        name: "{{rg_group_name}}"
        location: centralindia
        tags:
          environment: "{{environment_name}}"
          
    - name: 2 Create a windows app service plan
      azure_rm_appserviceplan:
        resource_group: "{{rg_group_name}}"
        name: "{{app_service_plan_name}}"
        location: centralindia
        sku: S1
        tags:
          environment: "{{environment_name}}"      
          
    - name: 3 Create a windows web app service with non-exist app service plan
      azure_rm_webapp:
        resource_group: "{{rg_group_name}}"
        name: "{{app_service_name}}"
        plan:
          resource_group: myappserviceplan_rg
          name: "{{app_service_plan_name}}"
          is_linux: false
          sku: S1
          tags:
          environment: "{{environment_name}}"
        
       