---
- name: Create Azure resource group
  hosts: localhost
  connection: local
  
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: kumarjk-rg
        location: centralindia
