---
- name: Create Azure resource group
  hosts: localhost
  connection: local
  
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: myresourcegroup-jk
        location: centralindia
        tags:
          testing: testing
          delete: never