---
- name: Create Azure resource group
  hosts: localhost
  connection: local
  vars:
    tenant_id: 8f286d24-172e-4e09-b0f0-76f2cf5786ea
    object_id: 862a7df6-74ba-445a-bc67-33701ffa10dc
    rg_group_name: "dev01resourcegroupjk02"
    location_name: "centralindia"
    vault_name: "samplekeyvaultjk01"
    environment_name: "DEV"
      
  tasks:
    - name: 1 Create a resource group
      azure_rm_resourcegroup:
        name: "{{rg_group_name}}"
        location: "{{location_name}}"
        tags:
          environment: "{{environment_name}}"

    - name: 2 Create a Keyvault
      azure_rm_keyvault:
        resource_group: "{{rg_group_name}}"
        vault_name: "{{ vault_name }}"
        enabled_for_deployment: yes
        vault_tenant: "{{ tenant_id }}"
        sku:
          name: standard
        access_policies:
          - tenant_id: "{{ tenant_id }}"
            object_id: "{{ object_id }}"
            secrets:
              - get
              - list
              - set
              - delete     
        tags:
          environment: "{{environment_name}}"
              
    - name: 3 Create a secretkey in keyvault
      azure_rm_keyvaultsecret:
        secret_name: MySecretjk
        secret_value: 123456789
        keyvault_uri: https://samplekeyvaultjk01.vault.azure.net/