---
- name: Create Azure resource group and storage account
  hosts: localhost
  connection: local
  vars:
    rg_group_name: dev02resourcegroupjk
    storage_account_name: dev02storageaccountjk
    container_name: foo
    environment_name: "DEV"

  
  tasks:
    - name: 1 Create a resource group
      azure_rm_resourcegroup:
        name: "{{rg_group_name}}"
        location: centralindia
        tags:
          environment: "{{environment_name}}"
                 
    - name: 2 create a storage account
      azure_rm_storageaccount:
        resource_group: "{{rg_group_name}}"
        name: "{{storage_account_name}}"
        type: Standard_RAGRS
        kind: BlobStorage
        tags:
          environment: "{{environment_name}}"

    - name: 3 Create container foo and upload a file
      azure_rm_storageblob:
        resource_group: "{{rg_group_name}}"
        storage_account_name: "{{storage_account_name}}"
        container: "{{container_name}}"          